---
- hosts: 35.190.174.154
  become: true
  tasks:
    - name: Install Packages
      yum: name={{item}} state=installed
      with_items:
        - vim
        - telnet
        - wget
        - gzip
        - unzip
        - net-tools
